language: java
jdk:
- oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sauce_connect:
    username: "SantiMA10"
    access_key:
      secure: "htJQ0nx/qJZIs+8D2YS4iPug8XqvZadpaIc1O4JxStednHxIN97ol1aMdb035RgG5CGLUIeHKMpDgHkQ5XZvYMiuwxyqRqKZLNnICmVm1a5rCPW1mLPM5zAGsBi9zi8KPeLzcMCYOLKCiujy4QRVlcEHD2xsgB/FpSYfRAi25F/iB7BT1sjqdihk391vSSQ1e0CcBoii5XuBRxcAhQhiwupzrQRKET0wARPsEQSoTRuRG0jZL47DqFbmYvcG5kmByiKZnMg+U76CBGJnxZsTPpLqNhtNDODGRUqx6pWLRoPGlVyDsggfpbiReDCn9DtrwkHXQQBzkUj6LokcEW+480UtuWoKtoQdLO3KfkzDoPGtOdu6wp7/aa2jVekwVcnoDGMBj4OnbEKeF1ciEU0WaOztaa7kI3LHfpdPWRZsoUIy+Y9bzYgVZ7GyR4/YWPwKM85ojaKzIdPP/SkdySjAiG8DCR6NKPMbSQFBD7/WFlQEYD0YVvbUj5w0iz5Sl/tiAJLasKnk+Wdm98RC7baBE9IXAdS0vWakcOHWtHCZPzsgjl8bA72UbynmbiKkDEAJ1gCA8tLjga63oiUuEflTgJuQYHwN2EdwMZvNS6cFbTPWaIzOPJf1orUZQ6SNv2EZOf8gvEKrhoozn4r0cQi2/qoCt7VgFee8Inzc6xn7s0Y="
deploy:
  provider: heroku
  api_key:
    secure: "kcEJnv5nbgGxd7vkC22W/6ST/8JaOze/MKa3ocsgc09I74WFIX1ge4uRAI8DgMDD2Sv/iOoQNCTVlWhygluoDZmUCZ2eziwCC7jOU9pluqSWxnhoGuj00DeEhE3VAqFN4+Bbo8XlTp956P6I2XuHmQRcmM80WV//WiYwNqUEMqBlBZwayDYtHrAncELZEi670FjV3ix+iskHfNtK54beMAqxe1shblzrC5UiUcLQHK97cLYqQJ4HaWG4CENH2pcrLZvA5fnTNuRHI3+GzklC2MZOjYLyLmAw+B/RnIc77BPgAq1pZaRVgBouHQ1gK5HHtO/nEo1istdjdf00RcMF9rrLnTkIWx2ksw8MqOjDFdMRGEosBK1UzmNr1Z3crWqB0hSTEdle4Z0UamI9KtDMPukR1GpA19AXhMrySth6hdmLSJK5+/2UPfL+VJX2FHeIIGAoLKvXEOWSz+qaJhUhM32qLJoYhZd4WtKXoKUBczP4MeKiyu6gzYS/C+hmSd1LStnaSXkIRcxo/l7F9f87iyZtrQeNQMSNCChTiwtfb08dD8DrRoM9fP1gcN/tdjN8tT2Krfwoh7PMbNIZWEEiE8hALNSD/wvG+m+ZVwnMIQyVt5kAB2x9X2bHGfmB6pFlGLyaqZMCtIdgRfpKgukJJqPMKKkSdYwZk4RcAX60FxQ="
  on: master
  app: voting-system-1b
